package gg.sbs.api.hypixel;

public class Testing {
/*

DUNGEON_SPECIAL
KILLS_BLAZE_HIGHER_OR_LOWER(Category.DUNGEON_SPECIAL, Location.THE_CATACOMBS),
KILLS_DUNGEON_SECRET_BAT(Category.DUNGEON_SPECIAL, Location.THE_CATACOMBS),
KILLS_DUNGEON_RESPAWNING_SKELETON(Category.DUNGEON_SPECIAL, Location.THE_CATACOMBS),
KILLS_DUNGEON_RESPAWNING_SKELETON_SKULL(Category.DUNGEON_SPECIAL, Location.THE_CATACOMBS),
DEATHS_TRAP(Category.DUNGEON_SPECIAL, Location.THE_CATACOMBS),
DEATHS_SKELETOR(Category.DUNGEON_SPECIAL, Location.THE_CATACOMBS),

DUNGEON_BOSSES
KILLS_SCARF(Category.DUNGEON_BOSSES, Location.THE_CATACOMBS),
DEATHS_SCARF(Category.DUNGEON_BOSSES, Location.THE_CATACOMBS),

DUNGEON_MINIBOSSES
KILLS_BONZO_SUMMON_UNDEAD(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_DEATHMITE(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_DIAMOND_GUY(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_KING_MIDAS(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_LOST_ADVENTURER(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_PROFESSOR_GUARDIAN_SUMMON(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_SCARF_ARCHER(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_SCARF_MAGE(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_SCARF_PRIEST(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_SCARF_WARRIOR(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_SHADOW_ASSASSIN(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_WATCHER_BONZO(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
KILLS_WATCHER_SUMMON_UNDEAD(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
DEATHS_DEATHMITE(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
DEATHS_DIAMOND_GUY(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
DEATHS_KING_MIDAS(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
DEATHS_LOST_ADVENTURER(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
DEATHS_PROFESSOR_MAGE_GUARDIAN(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
DEATHS_SHADOW_ASSASSIN(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),
DEATHS_WATCHER_SUMMON_UNDEAD(Category.DUNGEON_MINIBOSSES, Location.THE_CATACOMBS),

DUNGEON_ROYALS
KILLS_CRYPT_UNDEAD_ALEXANDER(Category.DUNGEON_ROYALS, Location.THE_CATACOMBS),
KILLS_CRYPT_UNDEAD_BERNHARD(Category.DUNGEON_ROYALS, Location.THE_CATACOMBS),
KILLS_CRYPT_UNDEAD_CHRISTIAN(Category.DUNGEON_ROYALS, Location.THE_CATACOMBS),
KILLS_CRYPT_UNDEAD_FRIEDRICH(Category.DUNGEON_ROYALS, Location.THE_CATACOMBS),
KILLS_CRYPT_UNDEAD_MARIUS(Category.DUNGEON_ROYALS, Location.THE_CATACOMBS),
KILLS_CRYPT_UNDEAD_NICHOLAS(Category.DUNGEON_ROYALS, Location.THE_CATACOMBS),
KILLS_CRYPT_UNDEAD_PIETER(Category.DUNGEON_ROYALS, Location.THE_CATACOMBS),
KILLS_CRYPT_UNDEAD_VALENTIN(Category.DUNGEON_ROYALS, Location.THE_CATACOMBS),

 */
}