INSERT INTO `accessory_families` (`name`, `reforges_stack`, `items_stack`) VALUES
    ('Speed', 0, 0),
    ('Feather', 0, 0),
    ('Piggy Bank', 0, 0),
    ('Potion Affinity', 0, 0),
    ('Healing', 0, 0),
    ('Sea Creature', 0, 0),
    ('Personal Compactor', 0, 0),
    ('Personal Deletor', 0, 0),
    ('Titanium', 0, 0),
    ('Power', 0, 0),
    ('Zombie', 0, 0),
    ('Intimidation', 0, 0),
    ('Bat', 0, 0),
    ('Candy', 0, 0),
    ('Beastmaster Crest', 0, 0),
    ('Sharktooth Necklace', 0, 0),
    ('Jerry Talisman', 0, 0),
    ('Bat Person', 0, 0),
    ('Spider', 0, 0),
    ('Wolf', 0, 0),
    ('Hoof', 0, 0),
    ('Red Claw', 0, 0),
    ('Hunter', 0, 0),
    ('Soulflow', 0, 0),
    ('Dark Auction', 0, 0),
    ('Dungeon Hub Race', 0, 0),
    ('Campfire Badge', 0, 0),
    ('Romero', 0, 0),
    ('Scarf''s', 0, 0),
    ('Treasure', 0, 0),
    ('Master Skull', 0, 0),
    ('Wither', 0, 0),
    ('Ender', 0, 0)
;