INSERT INTO `accessories` (`item_id`, `family`, `family_rank`, `name`, `rarity`, `effects`) VALUES
    ('FARMING_TALISMAN', NULL, NULL, 'Farming Talisman', 1, '{}'),
    ('VACCINE_TALISMAN', NULL, NULL, 'Vaccine Talisman', 1, '{}'),
    ('FARMER_ORB', NULL, NULL, 'Farmer Orb', 2, '{}'),
    ('NIGHT_VISION_CHARM', NULL, NULL, 'Night Vision Charm', 1, '{}'),
    ('SPEED_TALISMAN', 1, 1, 'Speed Talisman', 1, '{"spd":1}'),
    ('SPEED_RING', 1, 2, 'Speed Ring', 2, '{"spd":3}'),
    ('SPEED_ARTIFACT', 1, 3, 'Speed Artifact', 3, '{"spd":5}'),
    ('FEATHER_TALISMAN', 2, 1, 'Feather Talisman', 1, '{}'),
    ('FEATHER_RING', 2, 2, 'Feather Ring', 2, '{}'),
    ('FEATHER_ARTIFACT', 2, 3, 'Feather Artifact', 3, '{}'),
    ('PIGGY_BANK', 3, 1, 'Piggy Bank', 2, '{}'),
    ('POTION_AFFINITY_TALISMAN', 4, 1, 'Potion Affinity Talisman', 1, '{}'),
    ('RING_POTION_AFFINITY', 4, 2, 'Potion Affinity Ring', 2, '{}'),
    ('ARTIFACT_POTION_AFFINITY', 4, 3, 'Potion Affinity Artifact', 3, '{}'),
    ('HASTE_RING', NULL, NULL, 'Haste Ring', 3, '{}'),
    ('EXPERIENCE_ARTIFACT', NULL, NULL, 'Experience Artifact', 4, '{}'),
    ('COIN_TALISMAN', NULL, NULL, 'Talisman of Coins', 1, '{}'),
    ('MAGNETIC_TALISMAN', NULL, NULL, 'Magnetic Talisman', 2, '{}'),
    ('EMERALD_RING', NULL, NULL, 'Emerald Ring', 2, '{}'),
    ('NIGHT_CRYSTAL', NULL, NULL, 'Night Crystal', 3, '{}'),
    ('DAY_CRYSTAL', NULL, NULL, 'Day Crystal', 3, '{}'),
    ('GRAVITY_TALISMAN', NULL, NULL, 'Gravity Talisman', 2, '{}'),
    ('FIRE_TALISMAN', NULL, NULL, 'Fire Talisman', 1, '{}'),
    ('LAVA_TALISMAN', NULL, NULL, 'Lava Talisman', 2, '{}'),
    ('WOOD_TALISMAN', NULL, NULL, 'Wood Affinity Talisman', 2, '{}'),
    ('HEALING_TALISMAN', 5, 1, 'Healing Talisman', 1, '{}'),
    ('HEALING_RING', 5, 2, 'Healing Ring', 2, '{}'),
    ('BAIT_RING', 34, 1, 'Bait Ring', 3, '{}'),
    ('SEA_CREATURE_TALISMAN', 6, 1, 'Sea Creature Talisman', 1, '{}'),
    ('SEA_CREATURE_RING', 6, 2, 'Sea Creature Ring', 2, '{}'),
    ('SEA_CREATURE_ARTIFACT', 6, 3, 'Sea Creature Artifact', 3, '{}'),
    ('PERSONAL_COMPACTOR_4000', 7, 1, 'Personal Compactor 4000', 2, '{}'),
    ('PERSONAL_COMPACTOR_5000', 7, 2, 'Personal Compactor 5000', 3, '{}'),
    ('PERSONAL_COMPACTOR_6000', 7, 3, 'Personal Compactor 6000', 4, '{}'),
    ('PERSONAL_COMPACTOR_7000', 7, 4, 'Personal Compactor 7000', 5, '{}'),
    ('PERSONAL_DELETOR_4000', 8, 1, 'Personal Deletor 4000', 2, '{}'),
    ('PERSONAL_DELETOR_5000', 8, 2, 'Personal Deletor 5000', 3, '{}'),
    ('PERSONAL_DELETOR_6000', 8, 3, 'Personal Deletor 6000', 4, '{}'),
    ('PERSONAL_DELETOR_7000', 8, 4, 'Personal Deletor 7000', 5, '{}'),
    ('TITANIUM_TALISMAN', 9, 1, 'Titanium Talisman', 2, '{"minSpd":15}'),
    ('TITANIUM_RING', 9, 2, 'Titanium Ring', 3, '{"minSpd":30}'),
    ('TITANIUM_ARTIFACT', 9, 3, 'Titanium Artifact', 4, '{"minSpd":45}'),
    ('TITANIUM_RELIC', 9, 4, 'Titanium Relic', 5, '{"minSpd":60}'),
    ('POWER_TALISMAN', 10, 1, 'Talisman of Power', 1, '{}'),
    ('POWER_RING', 10, 2, 'Ring of Power', 2, '{}'),
    ('POWER_ARTIFACT', 10, 3, 'Artifact of Power', 3, '{}'),

    ('ZOMBIE_TALISMAN', 11, 1, 'Zombie Talisman', 1, '{}'),
    ('SKELETON_TALISMAN', NULL, NULL, 'Skeleton Talisman', 1, '{}'),
    ('VILLAGE_TALISMAN', NULL, NULL, 'Village Affinity Talisman', 1, '{}'),
    ('MINE_TALISMAN', NULL, NULL, 'Mine Affinity Talisman', 1, '{}'),
    ('INTIMIDATION_TALISMAN', 12, 1, 'Intimidation Talisman', 1, '{}'),
    ('SCAVENGER_TALISMAN', NULL, NULL, 'Scavenger Talisman', 1, '{}'),
    ('BITS_TALISMAN', NULL, NULL, 'Bits Talisman', 3, '{}'),
    ('DANTE_TALISMAN', NULL, NULL, 'Dante Talisman', 1, '{}'),
    ('BLOOD_GOD_CREST', NULL, NULL, 'Blood God Crest', 1, '{}'),
    ('BAT_RING', 13, 2, 'Bat Ring', 4, '{"hp":3,"spd":2,"int":2}'),
    ('BAT_ARTIFACT', 13, 3, 'Bat Artifact', 5, '{"hp":5,"spd":3,"int":3}'),
    ('CANDY_TALISMAN', 14, 1, 'Candy Talisman', 2, '{}'),
    ('CANDY_RING', 14, 2, 'Candy Ring', 3, '{}'),
    ('CANDY_ARTIFACT', 14, 3, 'Candy Artifact', 4, '{}'),
    ('CANDY_RELIC', 14, 4, 'Candy Relic', 5, '{}'),
    ('INTIMIDATION_RING', 12, 2, 'Intimidation Ring', 2, '{}'),
    ('INTIMIDATION_ARTIFACT', 12, 3, 'Intimidation Artifact', 3, '{}'),
    ('JUNGLE_AMULET', NULL, NULL, 'Jungle Amulet', 2, '{}'),

    ('NEW_YEAR_CAKE_BAG', NULL, NULL, 'New Year Cake Bag', 2, '{}'),
    ('PARTY_HAT_CRAB', NULL, NULL, 'Crab Hat of Celebration', 1, '{}'),
    ('POTATO_TALISMAN', NULL, NULL, 'Potato Talisman', 1, '{"spd":1}'),
    ('BEASTMASTER_CREST_COMMON', 15, 1, 'Beastmaster Crest', 1, '{}'),
    ('BEASTMASTER_CREST_UNCOMMON', 15, 2, 'Beastmaster Crest', 2, '{}'),
    ('BEASTMASTER_CREST_RARE', 15, 3, 'Beastmaster Crest', 3, '{}'),
    ('BEASTMASTER_CREST_EPIC', 15, 4, 'Beastmaster Crest', 4, '{}'),
    ('BEASTMASTER_CREST_LEGENDARY', 15, 5, 'Beastmaster Crest', 5, '{}'),
    ('MINERAL_TALISMAN', NULL, NULL, 'Mineral Talisman', 3, '{}'),
    ('RAGGEDY_SHARK_TOOTH_NECKLACE', 16, 1, 'Raggedy Shark Tooth Necklace', 1, '{"str":2}'),
    ('DULL_SHARK_TOOTH_NECKLACE', 16, 2, 'Dull Shark Tooth Necklace', 2, '{"str":4}'),
    ('HONED_SHARK_TOOTH_NECKLACE', 16, 3, 'Honed Shark Tooth Necklace', 3, '{"str":6}'),
    ('SHARP_SHARK_TOOTH_NECKLACE', 16, 4, 'Sharp Shark Tooth Necklace', 4, '{"str":8}'),
    ('RAZOR_SHARP_SHARK_TOOTH_NECKLACE', 16, 5, 'Razor-sharp Shark Tooth Necklace', 5, '{"str":10}'),
    ('JERRY_TALISMAN_GREEN', 17, 1, 'Green Jerry Talisman', 2, '{"int":-1}'),
    ('JERRY_TALISMAN_BLUE', 17, 2, 'Blue Jerry Talisman', 3, '{"int":-2}'),
    ('JERRY_TALISMAN_PURPLE', 17, 3, 'Purple Jerry Talisman', 4, '{"int":-3}'),
    ('JERRY_TALISMAN_GOLDEN', 17, 4, 'Golden Jerry Artifact', 5, '{"int":-4}'),
    ('BAT_PERSON_TALISMAN', 18, 1, 'Bat Person Talisman', 1, '{}'),
    ('BAT_PERSON_RING', 18, 2, 'Bat Person Ring', 2, '{}'),
    ('BAT_PERSON_ARTIFACT', 18, 3, 'Bat Person Artifact', 3, '{}'),

    ('BAT_TALISMAN', 13, 1, 'Bat Talisman', 3, '{"hp":1,"spd":1,"int":1}'),
    ('SPIDER_TALISMAN', 19, 1, 'Spider Talisman', 2, '{}'),
    ('FISH_AFFINITY_TALISMAN', NULL, NULL, 'Fish Affinity Talisman', 3, '{}'),
    ('WOLF_TALISMAN', 20, 1, 'Wolf Talisman', 1, '{}'),
    ('TARANTULA_TALISMAN', NULL, NULL, 'Tarantula Talisman', 4, '{}'),
    ('LUCKY_HOOF', 21, 1, 'Lucky Hoof', 2, '{}'),
    ('POCKET_ESPRESSO_MACHINE', NULL, NULL, 'Pocket Espresso Machine', 1, '{}'),
    ('HANDY_BLOOD_CHALICE', NULL, NULL, 'Handy Blood Chalice', 1, '{}'),

    ('ZOMBIE_RING', 11, 2, 'Zombie Ring', 2, '{}'),
    ('DEVOUR_RING', NULL, NULL, 'Devour Ring', 3, '{}'),
    ('ZOMBIE_ARTIFACT', 11, 3, 'Zombie Artifact', 3, '{}'),
    ('REAPER_ORB', NULL, NULL, 'Reaper Orb', 5, '{}'),
    ('SPIDER_RING', 19, 2, 'Spider Ring', 3, '{}'),
    ('SPIDER_ARTIFACT', 19, 3, 'Spider Artifact', 4, '{}'),
    ('SURVIVOR_CUBE', NULL, NULL, 'Survivor Cube', 3, '{}'),
    ('RED_CLAW_TALISMAN', 22, 1, 'Red Claw Talisman', 2, '{"cd":1}'),
    ('RED_CLAW_RING', 22, 2, 'Red Claw Ring', 3, '{"cd":3}'),
    ('RED_CLAW_ARTIFACT', 22, 3, 'Red Claw Artifact', 4, '{"cd":5}'),
    ('HUNTER_TALISMAN', 23, 1, 'Hunter Talisman', 2, '{}'),
    ('HUNTER_RING', 23, 2, 'Hunter Ring', 3, '{}'),
    ('SOULFLOW_PILE', 24, 1, 'Soulflow Pile', 2, '{}'),
    ('SOULFLOW_BATTERY', 24, 2, 'Soulflow Battery', 3, '{}'),
    ('SOULFLOW_SUPERCELL', 24, 3, 'Soulflow Supercell', 4, '{}'),
    ('ENDER_RELIC', 33, 2, 'Ender Relic', 5, '{}'),

    ('PIGS_FOOT', NULL, NULL, 'Pig''s Foot', 3, '{"spd":1}'),
    ('WOLF_PAW', NULL, NULL, 'Wolf Paw', 2, '{"spd":1}'),
    ('MELODY_HAIR', NULL, NULL, 'Melody''s Hair', 4, '{"int":6}'),
    ('SHADY_RING', 25, 1, 'Shady Ring', 2, '{}'),
    ('CROOKED_ARTIFACT', 25, 2, 'Crooked Artifact', 3, '{}'),
    ('SEAL_OF_THE_FAMILY', 25, 3, 'Seal of the Family', 4, '{}'),
    ('FROZEN_CHICKEN', NULL, NULL, 'Frozen Chicken', 3, '{"spd":1}'),
    ('CAT_TALISMAN', 26, 1, 'Cat Talisman', 2, '{"spd":1}'),
    ('LYNX_TALISMAN', 26, 2, 'Lynx Talisman', 3, '{"spd":2}'),
    ('CHEETAH_TALISMAN', 26, 3, 'Cheetah Talisman', 4, '{"spd":3}'),
    ('KING_TALISMAN', NULL, NULL, 'King Talisman', 1, '{"minSpd":1}'),

    ('CAMPFIRE_TALISMAN_1', 27, 1, 'Campfire Initiate Badge', 1, '{}'),
    ('CAMPFIRE_TALISMAN_2', 27, 2, 'Campfire Initiate Badge', 1, '{}'),
    ('CAMPFIRE_TALISMAN_3', 27, 3, 'Campfire Initiate Badge', 1, '{}'),
    ('CAMPFIRE_TALISMAN_4', 27, 4, 'Campfire Adept Badge', 2, '{}'),
    ('CAMPFIRE_TALISMAN_5', 27, 5, 'Campfire Adept Badge', 2, '{}'),
    ('CAMPFIRE_TALISMAN_6', 27, 6, 'Campfire Adept Badge', 2, '{}'),
    ('CAMPFIRE_TALISMAN_7', 27, 7, 'Campfire Adept Badge', 2, '{}'),
    ('CAMPFIRE_TALISMAN_8', 27, 8, 'Campfire Cultist Badge', 3, '{}'),
    ('CAMPFIRE_TALISMAN_9', 27, 9, 'Campfire Cultist Badge', 3, '{}'),
    ('CAMPFIRE_TALISMAN_10', 27, 10, 'Campfire Cultist Badge', 3, '{}'),
    ('CAMPFIRE_TALISMAN_11', 27, 11, 'Campfire Cultist Badge', 3, '{}'),
    ('CAMPFIRE_TALISMAN_12', 27, 12, 'Campfire Cultist Badge', 3, '{}'),
    ('CAMPFIRE_TALISMAN_13', 27, 13, 'Campfire Scion Badge', 4, '{}'),
    ('CAMPFIRE_TALISMAN_14', 27, 14, 'Campfire Scion Badge', 4, '{}'),
    ('CAMPFIRE_TALISMAN_15', 27, 15, 'Campfire Scion Badge', 4, '{}'),
    ('CAMPFIRE_TALISMAN_16', 27, 16, 'Campfire Scion Badge', 4, '{}'),
    ('CAMPFIRE_TALISMAN_17', 27, 17, 'Campfire Scion Badge', 4, '{}'),
    ('CAMPFIRE_TALISMAN_18', 27, 18, 'Campfire Scion Badge', 4, '{}'),
    ('CAMPFIRE_TALISMAN_19', 27, 19, 'Campfire Scion Badge', 4, '{}'),
    ('CAMPFIRE_TALISMAN_20', 27, 20, 'Campfire Scion Badge', 4, '{}'),
    ('CAMPFIRE_TALISMAN_21', 27, 21, 'Campfire God Badge', 5, '{}'),
    ('CAMPFIRE_TALISMAN_22', 27, 22, 'Campfire God Badge', 5, '{}'),
    ('CAMPFIRE_TALISMAN_23', 27, 23, 'Campfire God Badge', 5, '{}'),
    ('CAMPFIRE_TALISMAN_24', 27, 24, 'Campfire God Badge', 5, '{}'),
    ('CAMPFIRE_TALISMAN_25', 27, 25, 'Campfire God Badge', 5, '{}'),
    ('CAMPFIRE_TALISMAN_26', 27, 26, 'Campfire God Badge', 5, '{}'),
    ('CAMPFIRE_TALISMAN_27', 27, 27, 'Campfire God Badge', 5, '{}'),
    ('CAMPFIRE_TALISMAN_28', 27, 28, 'Campfire God Badge', 5, '{}'),
    ('CAMPFIRE_TALISMAN_29', 27, 29, 'Campfire God Badge', 5, '{}'),
    ('WEDDING_RING_0', 28, 1, 'Shiny Yellow Rock', 1, '{}'),
    ('WEDDING_RING_1', 28, 2, 'Yellow Rock of Love', 1, '{}'),
    ('WEDDING_RING_2', 28, 3, 'Mediocre Ring of Love', 2, '{}'),
    ('WEDDING_RING_3', 28, 4, 'Rubbish Ring of Love', 2, '{}'),
    ('WEDDING_RING_4', 28, 5, 'Modest Ring of Love', 3, '{}'),
    ('WEDDING_RING_5', 28, 6, 'Refined Ring of Love', 3, '{}'),
    ('WEDDING_RING_6', 28, 7, 'Classy Ring of Love', 3, '{}'),
    ('WEDDING_RING_7', 28, 8, 'Exquisite Ring of Love', 4, '{}'),
    ('WEDDING_RING_8', 28, 9, 'Invaluable Ring of Love', 4, '{}'),
    ('WEDDING_RING_9', 28, 10, 'Legendary Ring of Love', 5, '{}'),

    ('', NULL, NULL, '', 1, '{}'),
;