INSERT INTO `potions` (`key`, `name`, `description`, `buff`) VALUES
    ('WATER_BOTTLE', 'Water Bottle', '', 1),
    ('AWKWARD_POTION', 'Awkward Potion', '', 1),
    ('SPEED', 'Speed', 'Grants %{VALUE:PLUS} %{STAT:SPEED}.', 1),
    ('JUMP_BOOST', 'Jump Boost', 'Increases your jump height by %{VALUE,1} blocks.', 1),
    ('HEALING', 'Healing', 'Instantly heals you for %{VALUE} health.', 1),
    ('POISON', 'Poison', 'Poisons the affected, dealing damage over time.', 0),
    ('WATER_BREATHING', 'Water Breathing', 'Grants a %{VALUE:PERCENT} chance of not taking drowning damage.', 1),
    ('FIRE_RESISTANCE', 'Fire Resistance', 'Grants immunity to fire and lava.', 1),
    ('NIGHT_VISION', 'Night Vision', 'Grants greater visibility at night.', 1),
    ('STRENGTH', 'Strength', 'Increases %{STAT:STRENGTH} by %{VALUE,1}.', 1),
    ('INVISIBILITY', 'Invisibility', 'Grants invisibility from players and mobs.', 1),
    ('REGENERATION', 'Regeneration', 'Grants health regeneration of %{VALUE:PLUS,1} per second.', 1),
    ('WEAKNESS', 'Weakness', 'Reduces %{STAT:DAMAGE} when attacking enemies.', 0),
    ('SLOWNESS', 'Slowness', 'Reduces %{STAT:SPEED}.', 0),
    ('DAMAGE', 'Damage', 'Instantly deals %{VALUE} damage.', 0),
    ('HASTE', 'Haste', 'Increases your mining speed by %{VALUE:PERCENT}.', 1),
    ('RABBIT', 'Rabbit', 'Grants Jump Boost III and %{VALUE:SPEED:PLUS} %{STAT:SPEED}.', 1),
    ('BURNING', 'Burning', 'Damaging enemies sets them on fire, dealing %{VALUE} damage per second.', 1),
    ('KNOCKBACK', 'Knockback', 'Damaging enemies deals more knockback.', 0),
    ('VENOMOUS', 'Venomous', 'Grants a reduction in %{STAT:SPEED} and deals damage over time.', 0),
    ('STUN', 'Stun', 'When applied to yourself, your hits have a %{VALUE:STUN_CHANCE:PERCENT} chance to stun enemies for %{FORMAT:GREEN}1s%{FORMAT:GRAY}. When splashed, enemies are stunned for %{VALUE:STUN_DURATION}s.', 1),
    ('ARCHERY', 'Archery', 'Increases bow damage by %{VALUE:PERCENT}.', 1),
    ('ABSORPTION', 'Absorption', 'Grants %{VALUE:PLUS} of absorption.', 1),
    ('ADRENALINE', 'Adrenaline', 'Grants %{VALUE:ABSORPTION:PLUS} of absorption and %{VALUE:SPEED:PLUS} %{STAT:SPEED}.', 1),
    ('CRITICAL', 'Critical', 'Grants %{VALUE:CRIT_CHANCE} %{STAT:CRIT_CHANCE}, %{VALUE:CRIT_DAMAGE} %{STAT:CRIT_DAMAGE} and %{VALUE:MAGIC_FIND_BREW} %{STAT:MAGIC_FIND}.', 1),
    ('DODGE', 'Dodge', 'Mob attacks have a %{VALUE:PERCENT} chance to miss.', 1),
    ('AGILITY', 'Agility', 'Grants %{VALUE:SPEED:PLUS} %{STAT:SPEED} and increases the chance for mob attacks to miss by %{VALUE:DODGE_AGILITY:PERCENT}.', 1),
    ('WOUNDED', 'Wounded', 'Reduces healing by %{VALUE}.', 0),
    ('EXPERIENCE', 'Experience', 'Gain %{VALUE:EXPERIENCE_ORBS:PLUS:PERCENT}, %{VALUE:COMBAT_XP_BONUS_BREW:PLUS:PERCENT} Combat XP and regenerate %{VALUE:HEALTH_PER_SECOND_BREW}%{SYMBOL:HEALTH} per second.', 1),
    ('RESISTANCE', 'Resistance', 'Increases %{STAT:DEFENSE} by %{VALUE:PLUS}.', 1),
    ('MANA', 'Mana', 'Grants %{VALUE:PLUS} mana per second.', 1),
    ('STAMINA', 'Stamina', 'Instantly heals you for %{VALUE:INSTANT_HEALTH} health and gives %{VALUE:MANA} mana.', 1),
    ('BLINDNESS', 'Blindness', 'Blinds the affected player for %{VALUE}s.', 0),
    ('TRUE_RESISTANCE', 'True Resistance', 'Gain %{VALUE:PLUS} %{STAT:TRUE_DEFENSE}.', 1),
    ('PET_LUCK', 'Pet Luck', 'Gain %{VALUE:PLUS:PERCENT} chance to find pets and craft higher tier pets.', 1),
    ('SPELUNKER', 'Spelunker', 'Grants %{VALUE} %{STAT:MINING_FORTUNE}.', 1),
    ('SPIRIT', 'Spirit', 'Grants %{VALUE:SPEED:PLUS} %{STAT:SPEED} and %{VALUE:CRIT_DAMAGE:PLUS} %{STAT:CRIT_DAMAGE}.', 1),
    ('MAGIC_FIND', 'Magic Find', 'Gain %{VALUE:PLUS:PERCENT} chance to find rare items from monsters and bosses.', 1),
    ('KINGS_SCENT', 'King\'s Scent', 'Grants the stench of the Goblin King.', 1),
    ('FARMING_XP_BOOST', 'Farming XP Boost', 'Gain %{VALUE:PERCENT} more Farming experience.', 1),
    ('MINING_XP_BOOST', 'Mining XP Boost', 'Gain %{VALUE:PERCENT} more Mining experience.', 1),
    ('COMBAT_XP_BOOST', 'Combat XP Boost', 'Gain %{VALUE:PERCENT} more Combat experience.', 1),
    ('FORAGING_XP_BOOST', 'Foraging XP Boost', 'Gain %{VALUE:PERCENT} more Foraging experience.', 1),
    ('FISHING_XP_BOOST', 'Fishing XP Boost', 'Gain %{VALUE:PERCENT} more Fishing experience.', 1),
    ('ENCHANTING_XP_BOOST', 'Enchanting XP Boost', 'Gain %{VALUE:PERCENT} more Enchanting experience.', 1),
    ('ALCHEMY_XP_BOOST', 'Alchemy XP Boost', 'Gain %{VALUE:PERCENT} more Alchemy experience.', 1),
    ('JERRY_CANDY', 'Jerry Candy', 'Increases a bunch of stats!', 1);