CREATE TABLE `items` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(127) NOT NULL,
    `material` VARCHAR(127),
    `durability` INT,
    `skin` VARCHAR(1023),
    `furniture` VARCHAR(127),
    `tier` VARCHAR(15),
    `item_id` VARCHAR(127),
    `generator` VARCHAR(127),
    `generator_tier` INT,
    `glowing` TINYINT(1),
    `category` VARCHAR(31),
    `stats` JSON,
    `npc_sell_price` DOUBLE,
    `unstackable` TINYINT(1),
    `dungeon_item` TINYINT(1),
    `color` VARCHAR(31),
    `tiered_stats` JSON,
    `gear_score` INT,
    `requirements` JSON,
    `catacombs_requirements` JSON,
    `essence` JSON,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (`id`)
);