ALTER TABLE `minions` ADD COLUMN `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() AFTER `collection`;
ALTER TABLE `minion_items` ADD COLUMN `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() AFTER `yield`;
ALTER TABLE `minion_tiers` ADD COLUMN `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() AFTER `speed`;
ALTER TABLE `minion_tier_upgrades` ADD COLUMN `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() AFTER `quantity`;