DROP TABLE IF EXISTS `pet_items`;
CREATE TABLE `pet_items` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`item_id` VARCHAR(127) NOT NULL,
	`description` LONGTEXT NOT NULL DEFAULT '' COLLATE 'utf8mb4_bin',
	`percentage` TINYINT(1) NOT NULL DEFAULT '0',
	`effects` LONGTEXT NOT NULL DEFAULT '{}' COLLATE 'utf8mb4_bin',
	`buff_effects` LONGTEXT NOT NULL DEFAULT '{}' COLLATE 'utf8mb4_bin',
	`updated_at` TIMESTAMP NOT NULL DEFAULT current_timestamp(),

	PRIMARY KEY (`id`),
	UNIQUE KEY `item_id` (`item_id`),
	CONSTRAINT `pet_items_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `items` (`item_id`),
	CONSTRAINT `pet_items_chk_1` CHECK (`percentage` between 0 and 1),
	CONSTRAINT `pet_items_chk_2` CHECK (json_valid(`effects`)),
	CONSTRAINT `pet_items_chk_3` CHECK (json_valid(`buff_effects`))
);

INSERT INTO `pet_items` (`item_id`, `description`, `percentage`, `effects`, `buff_effects`) VALUES
    ('PET_ITEM_ALL_SKILLS_BOOST_COMMON', 'Gives %{VALUE:PLUS:PERCENT} pet exp for all skills.', 1, '{}', '{"PET_EXP":10}'),
    ('ALL_SKILLS_SUPER_BOOST', 'Gives %{VALUE:PLUS:PERCENT} pet exp for all skills.', 1, '{}', '{"PET_EXP":20}'),
    ('PET_ITEM_FARMING_SKILL_BOOST_COMMON', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Farming.', 1, '{}', '{"PET_FARMING_EXP":20}'),
    ('PET_ITEM_FARMING_SKILL_BOOST_UNCOMMON', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Farming.', 1, '{}', '{"PET_FARMING_EXP":30}'),
    ('PET_ITEM_FARMING_SKILL_BOOST_RARE', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Farming.', 1, '{}', '{"PET_FARMING_EXP":40}'),
    ('PET_ITEM_FARMING_SKILL_BOOST_EPIC', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Farming.', 1, '{}', '{"PET_FARMING_EXP":50}'),
    ('PET_ITEM_MINING_SKILL_BOOST_COMMON', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Mining', 1, '{}', '{"PET_MINING_EXP":20}'),
    ('PET_ITEM_MINING_SKILL_BOOST_RARE', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Mining.', 1, '{}', '{"PET_MINING_EXP":40}'),
    ('PET_ITEM_COMBAT_SKILL_BOOST_COMMON', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Combat.', 1, '{}', '{"PET_COMBAT_EXP":20}'),
    ('PET_ITEM_COMBAT_SKILL_BOOST_UNCOMMON', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Combat.', 1, '{}', '{"PET_COMBAT_EXP":30}'),
    ('PET_ITEM_COMBAT_SKILL_BOOST_RARE', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Combat.', 1, '{}', '{"PET_COMBAT_EXP":40}'),
    ('PET_ITEM_COMBAT_SKILL_BOOST_EPIC', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Combat.', 1, '{}', '{"PET_COMBAT_EXP":50}'),
    ('PET_ITEM_FORAGING_SKILL_BOOST_COMMON', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Foraging.', 1, '{}', '{"PET_FORAGING_EXP":20}'),
    ('PET_ITEM_FORAGING_SKILL_BOOST_EPIC', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Foraging.', 1, '{}', '{"PET_FORAGING_EXP":50}'),
    ('PET_ITEM_FISHING_SKILL_BOOST_COMMON', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Fishing.', 1, '{}', '{"PET_FISHING_EXP":20}'),
    ('PET_ITEM_FISHING_SKILL_BOOST_UNCOMMON', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Fishing.', 1, '{}', '{"PET_FISHING_EXP":30}'),
    ('PET_ITEM_FISHING_SKILL_BOOST_RARE', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Fishing.', 1, '{}', '{"PET_FISHING_EXP":40}'),
    ('PET_ITEM_FISHING_SKILL_BOOST_EPIC', 'Gives %{VALUE:PLUS:PERCENT} pet exp for Fishing.', 1, '{}', '{"PET_FISHING_EXP":50}'),
    ('PET_ITEM_EXP_SHARE', 'While unequipped this pet gains %{VALUE:PERCENT} of the equipped pet\'s xp, this is split between all pets holding this item.', 1, '{}', '{"PET_SHARE_EXP":25}'),
    ('PET_ITEM_BIG_TEETH_COMMON', 'Increases %{STAT:CRIT_CHANCE} by %{VALUE:PLUS}.', 0, '{"CRIT_CHANCE":5}', '{}'),
    ('BIGGER_TEETH', 'Increases %{STAT:CRIT_CHANCE} by %{VALUE:PLUS}.', 0, '{"CRIT_CHANCE":10}', '{}'),
    ('PET_ITEM_SHARPENED_CLAWS_UNCOMMON', 'Increases %{STAT:CRIT_DAMAGE} by %{VALUE:PLUS}.', 0, '{"CRIT_DAMAGE":15}', '{}'),
    ('SERRATED_CLAWS', 'Increases %{STAT:CRIT_DAMAGE} by %{VALUE:PLUS}.', 0, '{"CRIT_DAMAGE":25}', '{}'),
    ('PET_ITEM_IRON_CLAWS_COMMON', 'Increases the pet\'s %{STAT:CRIT_DAMAGE} by %{VALUE:CRIT_DAMAGE:PERCENT} and %{STAT:CRIT_CHANCE} by %{STAT:CRIT_CHANCE:PERCENT}.', 1, '{"CRIT_DAMAGE":40,"CRIT_CHANCE":40}', '{}'),
    ('GOLD_CLAWS', 'Increases the pet\'s %{STAT:CRIT_DAMAGE} by %{VALUE:CRIT_DAMAGE:PERCENT} and %{STAT:CRIT_CHANCE} by %{STAT:CRIT_CHANCE:PERCENT}.', 1, '{"CRIT_DAMAGE":50,"CRIT_CHANCE":50}', '{}'),
    ('PET_ITEM_HARDENED_SCALES_UNCOMMON', 'Increases %{STAT:DEFENSE} by %{VALUE}.', 0, '{"DEFENSE":25}', '{}'),
    ('REINFORCED_SCALES', 'Increases %{STAT:DEFENSE} by %{VALUE}.', 0, '{"DEFENSE":40}', '{}'),
    ('PET_ITEM_TEXTBOOK', 'Increases the pet\'s %{STAT:INTELLIGENCE} by %{VALUE:PERCENT}.', 1, '{"INTELLIGENCE":100}', '{}'),
    ('PET_ITEM_LUCKY_CLOVER', 'Increases %{STAT:MAGIC_FIND} by %{VALUE}.', 0, '{"MAGIC_FIND":7}', '{}'),
    ('PET_ITEM_SADDLE', 'Increases horse speed by %{VALUE:HORSE_SPEED:PERCENT} and jump boost by %{VALUE:HORSE_JUMP_BOOST:PERCENT}.', 1, '{"HORSE_SPEED":50,"HORSE_JUMP_BOOST":100}', '{}'),
    ('PET_ITEM_BUBBLEGUM', 'Your pet fuses its power with placed %{FORMAT:GREEN}Orbs %{FORMAT:GRAY}to give them %{VALUE}x duration.', 0, '{}', '{"ORB_DURATION":2}'),
    ('PET_ITEM_TIER_BOOST', 'Boosts the %{FORMAT:GREEN}rarity %{FORMAT:GRAY}of your pet by 1 tier!', 0, '{}', '{}'),
    ('PET_ITEM_VAMPIRE_FANG', 'Upgrades a Bat pet from %{SKILL:LEGENDARY} to %{SKILL:MYTHIC} adding a bonus perk and bonus stats!', 0, '{}', '{}'),
    ('PET_ITEM_TOY_JERRY', 'Upgrades a Jerry pet from %{SKILL:LEGENDARY} to %{SKILL:MYTHIC} and granting it a new perk!', 0, '{}', '{}'),
    ('PET_ITEM_SPOOKY_CUPCAKE', 'Increases %{STAT:STRENGTH} by %{VALUE:STRENGTH} and %{STAT:SPEED} by %{STAT:SPEED}.', 0, '{"STRENGTH":30,"SPEED":20}', '{}'),
    ('DWARF_TURTLE_SHELMET', 'Makes the pet\'s owner immune to knockback.', 0, '{}', '{}'),
    ('CROCHET_TIGER_PLUSHIE', 'Increases %{STAT:BONUS_ATTACK_SPEED} by %{VALUE}.', 0, '{"BONUS_ATTACK_SPEED":35}', '{}'),
    ('ANTIQUE_REMEDIES', 'Increases the pet\'s %{STAT:STRENGTH} by %{VALUE:PERCENT}.', 1, '{"STRENGTH":80}', '{}'),
    ('MINOS_RELIC', 'Increases all pet stats by %{VALUE:PERCENT}.', 1, '{}', '{"ALL_STATS":33.3}'),
    ('WASHED_UP_SOUVENIR', 'Increases %{STAT:SEA_CREATURE_CHANCE} by %{VALUE}.', 0, '{"SEA_CREATURE_CHANCE":5}', '{}'),
    ('REAPER_GEM', 'Gain %{VALUE} %{STAT:FEROCITY} for 5s on kill.', 0, '{}', '{"FEROCITY_ON_KILL":8}'),
    ('PET_ITEM_FLYING_PIG', 'Grants your pig pet the ability to fly while on your private island! You also don\'t need to hold a carrot on a stick to control your pig.', 0, '{}', '{}'),
    ('PET_ITEM_QUICK_CLAW', 'Every 2 pet levels, you gain +1 %{STAT:MINING_SPEED} and +1 %{STAT:MINING_FORTUNE}.', 0, '{}', '{"MINING_SPEED":"level/2","MINING_FORTUNE":"level/2"}');