INSERT INTO `locations` (`name`) VALUES
    ('Private Island'),
    ('Village'),
    ('Mountain'),
    ('Wilderness'),
    ('Ruins'),
    ('High Level'),
    ('Graveyard'),
    ('Dark Auction'),
    ('Farm'),
    ('Forest'),
    ('The Park'),
    ('The Barn'),
    ('Mushroom Desert'),
    ('Spider''s Den'),
    ('Blazing Fortress'),
    ('The End'),
    ('Void Sepulture'),
    ('Coal Mine'),
    ('Gold Mine'),
    ('Deep Caverns'),
    ('Jerry''s Workshop'),
    ('Dungeon Hub'),
    ('Limbo')
;